#!/usr/bin/env ruby -w -I./lib

require "demiurge"
require "demiurge/name_generator"

if ARGV.size < 1
  raise "Please give at least one Demiurge DSL file to parse!"
end

gen = Demiurge::NameGenerator.new
ARGV.each { |arg| gen.load_rules_from_demirule_string(File.read arg) }

names = gen.names
start_name = names.include?("start") ? "start" : names.first
gen_name = gen.generate_from_name start_name
STDERR.puts gen_name
