#!/usr/bin/env ruby -w -I./lib

require "demiurge"
require "demiurge/dsl"
require "demiurge/tmx"

require "multi_json"

if ARGV.size < 1
  raise "Please give at least one Demiurge DSL file to parse!"
end

engine = Demiurge.engine_from_dsl_files(*ARGV)

STDERR.puts "State:\n#{MultiJson.dump engine.structured_state, :pretty => true}"

intentions = engine.next_step_intentions
STDERR.puts "Intentions: #{intentions.inspect}"

engine.apply_intentions(intentions)

STDERR.puts "State:\n#{MultiJson.dump engine.structured_state, :pretty => true}"

STDERR.puts "Now two more steps..."
intentions = engine.next_step_intentions
engine.apply_intentions(intentions)
intentions = engine.next_step_intentions
engine.apply_intentions(intentions)
STDERR.puts "Finished! State:\n#{MultiJson.dump engine.structured_state, :pretty => true}"
