#!/usr/bin/env ruby -w -I./lib

require "demiurge"
require "demiurge/dsl"
require "demiurge/tmx"

require "multi_json"

if ARGV.size < 1
  raise "Please give at least one Demiurge DSL file to parse!"
end

engine = Demiurge.engine_from_dsl_files(*ARGV)
engine.finished_init

loop { engine.advance_one_tick }
