#!/usr/bin/env ruby -w -I./lib

require "demiurge"
require "demiurge/name_generator"

reps = 1
args = ARGV
if args.include?("-n")
  spot = args.index("-n")
  reps = args[spot + 1].to_i
  raise "No argument following -n!" unless reps
  args = args[0..(spot-1)] + args[(spot + 2)..-1]
end

if args.size < 1
  raise "Please give at least one Demiurge DSL file to parse!"
end

gen = Demiurge::NameGenerator.new
args.each { |arg| gen.load_rules_from_andor_string(File.read arg) }

names = gen.names
start_name = names.include?("start") ? "start" : names.first
reps.times do
  gen_name = gen.generate_from_name start_name
  puts gen_name
end
